# Generated by Django 4.2 on 2026-05-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the workflow', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the workflow')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the workflow was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the workflow was last updated')),
                ('data', models.JSONField(help_text='Workflow data in JSON format')),
            ],
        ),
    ]
