# Generated by Django 4.2 on 2026-05-12 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pitchdeck.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitchdeck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchDeckAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token', models.CharField(default=pitchdeck.models.generate_access_token, editable=False, max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('allowed_email', models.EmailField(blank=True, max_length=254)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uploads', models.PositiveIntegerField(default=1)),
                ('uploads_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='access_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pitchdeck.pitchdeckaccesslink'),
        ),
    ]
