# Generated by Django 4.2 on 2026-05-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitchdeck', '0002_pitchdeckaccesslink_pitchdeck_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitchdeck',
            options={'verbose_name': 'Discussion deck upload', 'verbose_name_plural': 'Discussion deck uploads'},
        ),
        migrations.AlterModelOptions(
            name='pitchdeckaccesslink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Discussion deck', 'verbose_name_plural': 'Discussion decks'},
        ),
    ]
