# Generated by Django 4.2 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_totp_secret",
            field=models.CharField(blank=True, max_length=64, verbose_name="Admin authenticator secret"),
        ),
        migrations.AddField(
            model_name="user",
            name="admin_totp_enabled",
            field=models.BooleanField(default=False, verbose_name="Admin authenticator enabled"),
        ),
    ]
